hydra:
  run:
    dir: outputs
    
model_type: openai
name: gpt4

api_type: "azure"

azure_api:
  api_key: ""
  azure_endpoint: "your-endpoint"
  api_version: "2023-05-15"

completion_config:
  model: "gpt-4"
  temperature: 1.0
  top_p: 0
  max_tokens: 300
  n: 20

batch_size: 1